---
- name: Set hostname
  ansible.builtin.copy:
    content: |
      {{ hostname | default('debian') }}
    dest: "{{ bootstrap_dir }}/etc/hostname"
    mode: 0644
    owner: root
    group: root

- name: Set hosts
  ansible.builtin.copy:
    content: |
      127.0.0.1        localhost
      ::1              localhost
      127.0.1.1        {{ hostname | default('debian') }} {{ hostname | default('debian') }}.{{ domain | default('at.home') }}
    dest: "{{ bootstrap_dir }}/etc/hosts"
    mode: 0644
    owner: root
    group: root

- name: Configure network interfaces
  ansible.builtin.copy:
    content: |
      auto lo
      iface lo inet loopback

      iface {{ main_if }} inet manual

      auto vmbr0
      iface vmbr0 inet {{ network_ip_address.type }}
          address {{ network_ip_address.address }}/{{ network_ip_address.mask_length }}
          gateway {{ network_ip_address.gateway }}
          broadcast {{ network_ip_address.broadcast }}
          bridge-ports {{ main_if }}
          bridge-stp off
          bridge-fd 0

    dest: "{{ bootstrap_dir }}/etc/network/interfaces"
    mode: 0644
    owner: root
    group: root
  when: network_ip_address.type == 'static'

- name: Configure resolv.conf
  ansible.builtin.copy:
    content: |
      nameservers {{ network_ip_address.gateway }}
      search {{ domain | default('at.home') }}

    dest: "{{ bootstrap_dir }}/etc/network/interfaces"
    mode: 0644
    owner: root
    group: root
  when: network_ip_address.type == 'static'

- name: Configure network interfaces
  ansible.builtin.copy:
    content: |
      auto lo
      iface lo inet loopback

      iface {{ main_if }} inet manual

      auto vmbr0
      iface vmbr0 inet {{ network_ip_address.type }}
          bridge-ports {{ main_if }}
          bridge-stp off
          bridge-fd 0

    dest: "{{ bootstrap_dir }}/etc/network/interfaces"
    mode: 0644
    owner: root
    group: root
  when: network_ip_address.type == 'dhcp'

- name: Configure resolv.conf
  ansible.builtin.copy:
    content: |
      nameserver 192.168.122.1

    dest: "{{ bootstrap_dir }}/etc/resolv.conf"
    mode: 0644
    owner: root
    group: root
  when: network_ip_address.type == 'static'

