---
- name: Find main inteface
  ansible.builtin.set_fact:
    main_if: "{{ network_interface[current_if].device }}"
  loop: "{{ network_interfaces }}"
  loop_control:
    loop_var: current_if
  when:
    network_interface[current_if].active and network_interface[current_if].device != "lo"

- name: Configure network interfaces
  ansible.builtin.copy:
    content: |
      auto lo
      iface lo inet loopback

      iface {{ main_if }} inet manual

      auto vmbr0
      iface vmbr0 inet static
          address 192.168.123.47/23
          gateway 192.168.122.1
          bridge-ports {{ main_if }}
          bridge-stp off
          bridge-fd 0

    dest: "{{ bootstrap_dir }}/etc/network/interfaces"
    mode: 0644
    owner: root
    group: root
