---
- name: Gather
  block:
    - name: Gather system information
      ansible.builtin.include_tasks: gather_system_information.yml
  tags:
    - gather_information

- name: Provision disk
  block:
    - name: Prepare installation medium
      ansible.builtin.include_tasks: provision_installation_disk.yml
  tags:
    - prepare_installation_medium
  when:
    - init is defined and init

- name: Get disk information
  block:
    - name: Get disk information
      ansible.builtin.include_tasks: get_disk_information.yml
  tags:
    - get_disk_information

- name: Prepare for installation
  block:
    - name: Mount filesystems
      ansible.builtin.include_tasks: mount_installation_medium.yml
  tags:
    - install_prep

- name: Install Debian base system
  block:
    - name: Bootstrap Debian
      ansible.builtin.include_tasks: bootstrap_debian.yml
  environment:
    DEBIAN_FRONTEND: noninteractive
    PATH: /bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
  tags:
    - bootstrap_debian
  when:
    - init is defined and init

- name: Configure System
  block:
    - name: Configure System
      ansible.builtin.include_tasks: configure_system.yml
  environment:
    DEBIAN_FRONTEND: noninteractive
    PATH: /bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
  tags:
    - configure_system

- name: Configure Network Debian
  block:
    - name: Configure Network
      ansible.builtin.include_tasks: configure_network_debian.yml
  environment:
    DEBIAN_FRONTEND: noninteractive
    PATH: /bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
  tags:
    - configure_network_debian

- name: Configure boot loader
  block:
    - name: Configure boot loader
      ansible.builtin.include_tasks: configure_grub_boot_loader.yml
  tags:
    - configure_boot_loader
  when:
    - init is defined and init

- name: Complete installation
  block:
    - name: Complete installation
      ansible.builtin.include_tasks: unmount_installation_medium.yml
  tags:
    - complete_installation
