---
- name: Provision disk
  block:
    - name: Prepare installation medium
      ansible.builtin.include_tasks: provision_installation_disk.yml
  tags:
    - prepare_installation_medium

- name: Prepare for installation
  block:
    - name: Mount filesystems
      ansible.builtin.include_tasks: mount_installation_medium.yml
  tags:
    - install_prep

- name: Install Debian
  block:
    - name: Bootstrap Debian
      ansible.builtin.include_tasks: bootstrap_debian.yml
  environment:
    DEBIAN_FRONTEND: noninteractive
    PATH: /bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
  tags:
    - bootstrap_debian

# - name: Prepare for reboot
#   block:
#     - name: Unmount filesystems
#       ansible.builtin.include_tasks: unmount_installation_medium.yml
#   tags:
#     - reboot_prep
# 