---
- name: Mount devices
  ansible.builtin.shell:
    cmd: |
      swapon {{ partition_info.swap }} && \
      mount {{ partition_info.root }} {{ bootstrap_dir }} && \
      mkdir {{ bootstrap_dir }}/boot && \
      mount {{ partition_info.efi }} {{ bootstrap_dir }}/boot

- name: Get device UUIDs
  ansible.builtin.shell:
    cmd: |
      lsblk -f --json | jq '.blockdevices[] | select (.name == "{{ installation_disk.name }}") | .children'
  register: get_uuid_result

- name: Set device info
  ansible.builtin.set_fact:
    device_info: "{{ get_uuid_result.stdout | from_json }}"

- name: Generate /etc/fstab
  ansible.builtin.copy:
    content: |
      # {{ partition_info.root }}
      UUID={{ (device_info | selectattr('fstype','equalto','ext4') | first).uuid }}	/         	ext4      	rw,relatime	0 1

      # {{ partition_info.efi }}
      UUID={{ (device_info | selectattr('fstype','equalto','vfat') | first).uuid }}                            	/boot     	vfat      	rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro	0 2

      # {{ partition_info.swap }}
      UUID={{ (device_info | selectattr('fstype','equalto','swap') | first).uuid }}	none      	swap      	defaults  	0 0

    dest: "{{ bootstrap_dir }}/etc/fstab"
    mode: 0644
    owner: root
    group: root
