---
- name: Mount devices
  ansible.builtin.shell:
    cmd: |
      swapon {{ partition_info.swap }} && \
      mount {{ partition_info.root }} {{ bootstrap_dir }} && \
      mkdir {{ bootstrap_dir }}/boot && \
      mount {{ partition_info.efi }} {{ bootstrap_dir }}/boot

- name: Get device UUIDs
  ansible.builtin.shell:
    cmd: |
      lsblk -f --json | jq '.blockdevices[] | select (.name == "{{ installation_disk.name }}") | .children'
  register: get_uuid_result

- name: Set device info
  ansible.builtin.set_fact:
    device_info: "{{ get_uuid_result.stdout | from_json }}"
